# Generated by Django 2.2.9 on 2020-03-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phno',
            new_name='phone_no',
        ),
    ]
