# Generated by Django 3.0 on 2020-03-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200302_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
        ),
    ]
