# Generated by Django 3.0 on 2020-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_contactus_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
